name: instagram_clone_mikolaj
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.1
  uuid: ^3.0.6
  hooks_riverpod: ^2.1.1
  cloud_firestore: ^4.0.4
  firebase_storage: ^11.0.4
  firebase_auth: ^4.1.1
  font_awesome_flutter: ^10.2.1
  flutter_facebook_auth: ^5.0.4
  google_sign_in: ^5.4.2
  image_picker: ^0.8.6
  image: ^3.2.2
  flutter_hooks: ^0.18.5+1
  collection: ^1.16.0
  intl: ^0.17.0
  video_thumbnail: ^0.5.3
  video_player: ^2.4.7
  lottie: ^1.4.3
  share_plus: ^6.2.0
  url_launcher: ^6.1.6
  riverpod_annotation: ^1.0.6
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  riverpod_generator: ^1.0.4

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/empty.json
    - assets/animations/loading.json
    - assets/animations/data_not_found.json
    - assets/animations/error.json
    - assets/animations/small_error.json
    - assets/animations/sign-in-or-sign-up-animation.json